version: "3"
services:
  db:
    image: mariadb:10
    container_name: satla-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: satla_password
      MARIADB_DATABASE: satla
      TZ: Asia/Tokyo
    ports:
      - 13706:3306
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/init:/docker-entrypoint-initdb.d
      - ./log/mariadb:/var/log/mysql
    entrypoint: |
      sh -c "
        echo \"CREATE DATABASE IF NOT EXISTS satla;\" > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
      "

  phpmyadmin:
    image: phpmyadmin:5
    container_name: satla-phpmyadmin
    restart: always
    ports:
      - 18083:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=satla_password
      - PMA_ARBITRARY=1

  redis:
    image: redis:7
    container_name: satla-redis
    restart: always
    environment:
      TZ: Asia/Tokyo
    ports:
      - 16769:6379
    volumes:
      - ./redis/data:/data
      - ./log/redis:/var/log/redis

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: satla-redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "13760:8081"
